# Generated by Django 4.1.2 on 2022-10-15 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0002_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_price', models.FloatField()),
                ('Stock_date', models.DateField()),
                ('Stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.stock')),
            ],
        ),
    ]
