# Generated by Django 4.1.2 on 2022-10-16 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StockApp', '0003_stockdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['Stock_id'], 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterModelOptions(
            name='stockdata',
            options={'ordering': ['id'], 'verbose_name_plural': 'StockData'},
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_price', models.FloatField()),
                ('Stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserStocks',
                'ordering': ['user'],
            },
        ),
    ]
