# Generated by Django 4.1.2 on 2022-10-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0004_alter_stock_options_alter_stockdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstocks',
            name='Stock_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
